name: Build image api

on:
  pull_request:
    types: [closed]
    branches:
      - "main"
      - "release/**"
      - "dev/**"
  workflow_dispatch:

jobs:
  update_images:
    name: Build image
    runs-on: ubuntu-latest
    environment: Product
    permissions:
      id-token: write
      contents: write
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build, tag, and push docker image to Docker hub
        run: |
          echo "${{ secrets.DOCKER_HUB_SECRETS }}" | docker login -u 1wolfalone1 --password-stdin
          docker build -t 1wolfalone1/mealsync-api:latest .
          docker push 1wolfalone1/mealsync-api:latest

  # sync-argocd:
  #   needs: update_images
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Sync ArgoCD Application
  #       uses: omegion/argocd-actions@v1
  #       with:
  #         address: "argocd-system.mealsync.org"
  #         token: ${{ secrets.ARGOCD_TOKEN }}
  #         action: sync
  #         appName: "backend-api"
  #
